# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.test_long_sword.root] run return 0
execute on passengers if entity @s[tag=aj.test_long_sword.data] unless data entity @s {data:{rigHash: '87d28824900a2b58fcbd82ebbe594ba93f8b10a95b273b5629219fa5556f84be'}} on vehicle run function animated_java:test_long_sword/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1