# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.test_long_sword.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.test_long_sword.animation.sweep1.playing] run function animated_java:test_long_sword/animations/sweep1/zzz/on_tick
execute if entity @s[tag=aj.test_long_sword.animation.sweep2.playing] run function animated_java:test_long_sword/animations/sweep2/zzz/on_tick
execute if entity @s[tag=aj.test_long_sword.animation.sweep3.playing] run function animated_java:test_long_sword/animations/sweep3/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~