# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.test_long_sword.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'test_long_sword', 'function_path': 'animated_java:test_long_sword/animations/sweep2/stop'}
tag @s remove aj.test_long_sword.animation.sweep2.playing
scoreboard players set @s aj.sweep2.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:test_long_sword/animations/sweep2/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only