# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.test_long_sword.node.1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.test_long_sword.node.2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.test_long_sword.node.3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.test_long_sword.node.4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_4 set from storage aj:uuid main.out