# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.test_long_sword.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'test_long_sword', 'function_path': 'animated_java:test_long_sword/animations/sweep3/next_frame'}
execute if score @s aj.sweep3.frame matches 21.. run scoreboard players set @s aj.sweep3.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.sweep3.frame
execute at @s run function animated_java:test_long_sword/animations/sweep3/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.sweep3.frame 1