# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.sweep1.frame dummy
scoreboard objectives add aj.sweep2.frame dummy
scoreboard objectives add aj.sweep3.frame dummy