# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.long_sword_id1.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'long_sword_id1', 'function_path': 'animated_java:long_sword_id1/remove/this'}
execute on passengers run kill @s
kill @s