# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.s0_sweep1.frame dummy
scoreboard objectives add aj.s0_sweep2.frame dummy
scoreboard objectives add aj.s0_sweep3.frame dummy
scoreboard objectives add aj.s1_sweep1.frame dummy
scoreboard objectives add aj.s1_sweep2.frame dummy
scoreboard objectives add aj.s1_sweep3.frame dummy
scoreboard objectives add aj.s1_dumb.frame dummy