# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.s0_sweep1.frame
scoreboard objectives remove aj.s0_sweep2.frame
scoreboard objectives remove aj.s0_sweep3.frame
scoreboard objectives remove aj.s1_sweep1.frame
scoreboard objectives remove aj.s1_sweep2.frame
scoreboard objectives remove aj.s1_sweep3.frame
scoreboard objectives remove aj.s1_dumb.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"long_sword_id1",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]