# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.long_sword_id1.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'long_sword_id1', 'function_path': 'animated_java:long_sword_id1/animations/s1_sweep3/stop'}
tag @s remove aj.long_sword_id1.animation.s1_sweep3.playing
scoreboard players set @s aj.s1_sweep3.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:long_sword_id1/animations/s1_sweep3/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only