# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.long_sword_id1.root] run return 0
execute on passengers if entity @s[tag=aj.long_sword_id1.data] unless data entity @s {data:{rigHash: 'b1fbb7a2ec78fe7229081d14fbbc25b4a807d0950b5fe389b9dbd9cdd00b8c9f'}} on vehicle run function animated_java:long_sword_id1/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1