# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.long_sword_id1.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.long_sword_id1.animation.s0_sweep1.playing] run function animated_java:long_sword_id1/animations/s0_sweep1/zzz/on_tick
execute if entity @s[tag=aj.long_sword_id1.animation.s0_sweep2.playing] run function animated_java:long_sword_id1/animations/s0_sweep2/zzz/on_tick
execute if entity @s[tag=aj.long_sword_id1.animation.s0_sweep3.playing] run function animated_java:long_sword_id1/animations/s0_sweep3/zzz/on_tick
execute if entity @s[tag=aj.long_sword_id1.animation.s1_sweep1.playing] run function animated_java:long_sword_id1/animations/s1_sweep1/zzz/on_tick
execute if entity @s[tag=aj.long_sword_id1.animation.s1_sweep2.playing] run function animated_java:long_sword_id1/animations/s1_sweep2/zzz/on_tick
execute if entity @s[tag=aj.long_sword_id1.animation.s1_sweep3.playing] run function animated_java:long_sword_id1/animations/s1_sweep3/zzz/on_tick
execute if entity @s[tag=aj.long_sword_id1.animation.s1_dumb.playing] run function animated_java:long_sword_id1/animations/s1_dumb/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~