# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.long_sword_id1.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'long_sword_id1', 'function_path': 'animated_java:long_sword_id1/animations/pause_all'}
tag @s remove aj.long_sword_id1.animation.s0_sweep1.playing
tag @s remove aj.long_sword_id1.animation.s0_sweep2.playing
tag @s remove aj.long_sword_id1.animation.s0_sweep3.playing
tag @s remove aj.long_sword_id1.animation.s1_sweep1.playing
tag @s remove aj.long_sword_id1.animation.s1_sweep2.playing
tag @s remove aj.long_sword_id1.animation.s1_sweep3.playing
tag @s remove aj.long_sword_id1.animation.s1_dumb.playing